# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(372, 524)
        MainWindow.setStyleSheet("background-color: rgb(20, 20, 20);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_res = QtWidgets.QLabel(self.centralwidget)
        self.label_res.setGeometry(QtCore.QRect(0, 0, 371, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setPointSize(24)
        font.setWeight(75)
        self.label_res.setFont(font)
        self.label_res.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                     "border-bottom-width: 2px;\n"
                                     "border-bottom-style: solid;\n"
                                     "border-radius: 0px;\n"
                                     "border-color: white;"
                                     "color: white;")
        self.label_res.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_res.setObjectName("label_res")
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zero.setGeometry(QtCore.QRect(0, 430, 181, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_zero.setFont(font)
        self.btn_zero.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "border: 2px solid white;\n"
                                    "border-radius: 45px;")
        self.btn_zero.setObjectName("btn_zero")
        self.btn_dot = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dot.setGeometry(QtCore.QRect(180, 430, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dot.setFont(font)
        self.btn_dot.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "border: 2px solid white;\n"
                                   "border-radius: 45px;")
        self.btn_dot.setObjectName("btn_dot")
        self.btn_one = QtWidgets.QPushButton(self.centralwidget)
        self.btn_one.setGeometry(QtCore.QRect(0, 340, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_one.setFont(font)
        self.btn_one.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "border: 2px solid white;\n"
                                   "border-radius: 45px;")
        self.btn_one.setObjectName("btn_one")
        self.btn_four = QtWidgets.QPushButton(self.centralwidget)
        self.btn_four.setGeometry(QtCore.QRect(0, 250, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_four.setFont(font)
        self.btn_four.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "border: 2px solid white;\n"
                                    "border-radius: 45px;")
        self.btn_four.setObjectName("btn_four")
        self.btn_seven = QtWidgets.QPushButton(self.centralwidget)
        self.btn_seven.setGeometry(QtCore.QRect(0, 160, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_seven.setFont(font)
        self.btn_seven.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "border: 2px solid white;\n"
                                     "border-radius: 45px;")
        self.btn_seven.setObjectName("btn_seven")
        self.btn_two = QtWidgets.QPushButton(self.centralwidget)
        self.btn_two.setGeometry(QtCore.QRect(90, 340, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_two.setFont(font)
        self.btn_two.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "border: 2px solid white;\n"
                                   "border-radius: 45px;")
        self.btn_two.setObjectName("btn_two")
        self.btn_five = QtWidgets.QPushButton(self.centralwidget)
        self.btn_five.setGeometry(QtCore.QRect(90, 250, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_five.setFont(font)
        self.btn_five.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "border: 2px solid white;\n"
                                    "border-radius: 45px;")
        self.btn_five.setObjectName("btn_five")
        self.btn_eight = QtWidgets.QPushButton(self.centralwidget)
        self.btn_eight.setGeometry(QtCore.QRect(90, 160, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_eight.setFont(font)
        self.btn_eight.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "border: 2px solid white;\n"
                                     "border-radius: 45px;")
        self.btn_eight.setObjectName("btn_eight")
        self.btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.btn_equal.setGeometry(QtCore.QRect(280, 430, 91, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_equal.setFont(font)
        self.btn_equal.setStyleSheet("background-color: rgb(255, 124, 0);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "border: 2px solid white;\n"
                                     "border-radius: 45px;")
        self.btn_equal.setObjectName("btn_equal")
        self.btn_six = QtWidgets.QPushButton(self.centralwidget)
        self.btn_six.setGeometry(QtCore.QRect(180, 250, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_six.setFont(font)
        self.btn_six.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                   "color: rgb(255, 255, 255);\n"
                                   "border: 2px solid white;\n"
                                   "border-radius: 45px;")
        self.btn_six.setObjectName("btn_six")
        self.btn_nine = QtWidgets.QPushButton(self.centralwidget)
        self.btn_nine.setGeometry(QtCore.QRect(180, 160, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_nine.setFont(font)
        self.btn_nine.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                    "color: rgb(255, 255, 255);\n"
                                    "border: 2px solid white;\n"
                                    "border-radius: 45px;")
        self.btn_nine.setObjectName("btn_nine")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(0, 80, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clear.setFont(font)
        self.btn_clear.setStyleSheet("background-color:rgb(112, 112, 112);\n"
                                     "color: white;\n"
                                     "border: 2px solid rgb(184, 184, 184);\n"
                                     "border-radius: 45px;")
        self.btn_clear.setObjectName("btn_clear")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(280, 350, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_add.setFont(font)
        self.btn_add.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                   "color: rgb(255, 124, 0);\n"
                                   "border: 2px solid rgb(255, 124, 0);\n"
                                   "border-radius: 45px;")
        self.btn_add.setObjectName("btn_add")
        self.btn_sub = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sub.setGeometry(QtCore.QRect(280, 260, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sub.setFont(font)
        self.btn_sub.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                   "color: rgb(255, 124, 0);\n"
                                   "border: 2px solid rgb(255, 124, 0);\n"
                                   "border-radius: 45px;")
        self.btn_sub.setObjectName("btn_sub")
        self.btn_mul = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mul.setGeometry(QtCore.QRect(280, 170, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_mul.setFont(font)
        self.btn_mul.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                   "color: rgb(255, 124, 0);\n"
                                   "border: 2px solid rgb(255, 124, 0);\n"
                                   "border-radius: 45px;")
        self.btn_mul.setObjectName("btn_mul")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(280, 80, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_div.setFont(font)
        self.btn_div.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                   "color: rgb(255, 124, 0);\n"
                                   "border: 2px solid rgb(255, 124, 0);\n"
                                   "border-radius: 45px;")
        self.btn_div.setObjectName("btn_div")
        self.btn_sqrt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sqrt.setGeometry(QtCore.QRect(90, 80, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sqrt.setFont(font)
        self.btn_sqrt.setStyleSheet("background-color:rgb(112, 112, 112);\n"
                                    "color: white;\n"
                                    "border: 2px solid rgb(184, 184, 184);\n"
                                    "border-radius: 45px;")
        self.btn_sqrt.setObjectName("btn_sqrt")
        self.btn_sqpow = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sqpow.setGeometry(QtCore.QRect(180, 80, 91, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_sqpow.setFont(font)
        self.btn_sqpow.setStyleSheet("background-color:rgb(112, 112, 112);\n"
                                  "color: white;\n"
                                  "border: 2px solid rgb(184, 184, 184);\n"
                                  "border-radius: 45px;")
        self.btn_sqpow.setObjectName("btn_sqpow")
        self.btn_three = QtWidgets.QPushButton(self.centralwidget)
        self.btn_three.setGeometry(QtCore.QRect(180, 340, 90, 90))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.btn_three.setFont(font)
        self.btn_three.setStyleSheet("background-color: rgb(20, 20, 20);\n"
                                     "color: rgb(255, 255, 255);\n"
                                     "border: 2px solid white;\n"
                                     "border-radius: 45px;")
        self.btn_three.setObjectName("btn_three")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

        self.isequal = False

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Какулятор"))
        self.label_res.setText(_translate("MainWindow", "0"))
        self.btn_zero.setText(_translate("MainWindow", "0"))
        self.btn_dot.setText(_translate("MainWindow", "."))
        self.btn_one.setText(_translate("MainWindow", "1"))
        self.btn_four.setText(_translate("MainWindow", "4"))
        self.btn_seven.setText(_translate("MainWindow", "7"))
        self.btn_two.setText(_translate("MainWindow", "2"))
        self.btn_five.setText(_translate("MainWindow", "5"))
        self.btn_eight.setText(_translate("MainWindow", "8"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn_six.setText(_translate("MainWindow", "6"))
        self.btn_nine.setText(_translate("MainWindow", "9"))
        self.btn_clear.setText(_translate("MainWindow", "C"))
        self.btn_add.setText(_translate("MainWindow", "+"))
        self.btn_sub.setText(_translate("MainWindow", "-"))
        self.btn_mul.setText(_translate("MainWindow", "*"))
        self.btn_div.setText(_translate("MainWindow", "÷"))
        self.btn_sqrt.setText(_translate("MainWindow", "√"))
        self.btn_sqpow.setText(_translate("MainWindow", "x^2"))
        self.btn_three.setText(_translate("MainWindow", "3"))

    def add_functions(self):
        # залинковали
        # кнопку с функцией записи числа,
        # передав в качестве аргумента функцию, которая в свою очередь возвращает то, что написано на данной кнопке
        self.btn_zero.clicked.connect(lambda: self.write_number(self.btn_zero.text()))
        self.btn_one.clicked.connect(lambda: self.write_number(self.btn_one.text()))
        self.btn_two.clicked.connect(lambda: self.write_number(self.btn_two.text()))
        self.btn_three.clicked.connect(lambda: self.write_number(self.btn_three.text()))
        self.btn_four.clicked.connect(lambda: self.write_number(self.btn_four.text()))
        self.btn_five.clicked.connect(lambda: self.write_number(self.btn_five.text()))
        self.btn_six.clicked.connect(lambda: self.write_number(self.btn_six.text()))
        self.btn_seven.clicked.connect(lambda: self.write_number(self.btn_seven.text()))
        self.btn_eight.clicked.connect(lambda: self.write_number(self.btn_eight.text()))
        self.btn_nine.clicked.connect(lambda: self.write_number(self.btn_nine.text()))
        self.btn_add.clicked.connect(lambda: self.write_number(self.btn_add.text()))
        self.btn_sub.clicked.connect(lambda: self.write_number(self.btn_sub.text()))
        self.btn_mul.clicked.connect(lambda: self.write_number(self.btn_mul.text()))
        self.btn_div.clicked.connect(lambda: self.write_number('/'))
        self.btn_dot.clicked.connect(lambda: self.write_number(self.btn_dot.text()))
        self.btn_equal.clicked.connect(self.res)
        
        self.btn_clear.clicked.connect(lambda: self.actions(int(self.label_res.text()), self.btn_clear.text()))
        self.btn_sqrt.clicked.connect(lambda: self.actions(int(self.label_res.text()), self.btn_sqrt.text()))
        self.btn_sqpow.clicked.connect(lambda: self.actions(int(self.label_res.text()), self.btn_sqpow.text()))

    def write_number(self, number):
        if self.label_res.text() == '0':
            self.label_res.setText(number)
            self.isequal = False
        else:
            self.label_res.setText(self.label_res.text() + number)

    def res(self):
        if not self.isequal:
            result = eval(self.label_res.text())
            self.label_res.setText(str(result))
            self.isequal = True
        else:
            error = QMessageBox()
            error.setWindowTitle("Вводите пжлст корректно")
            error.setText("Сейчас это действие недоступно")
            error.setIcon(QMessageBox.Warning)
            error.setStandardButtons(QMessageBox.Cancel|QMessageBox.Ok)

            error.setDefaultButton(QMessageBox.Ok)
            error.setInformativeText("Дважды выполнять нельзя")
            error.setDetailedText("Детали")

            error.exec_()


    def actions(self, number, action):
        if action == '√':
            self.label_res.setText(f'{number**0.5}')
        elif action == 'x^2':
            self.label_res.setText(f'{number**2}')
        elif action == 'C':
            self.label_res.setText('0')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
